apiVersion: apps/v1
kind: Deployment
metadata:
  name: modbot-deployment
spec:
  selector:
    matchLabels:
      app: modbot-app
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: modbot-app
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: modbot-container
        image: modbot
        imagePullPolicy: Always
        env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: token
